import * as core from "./core.js";
import {ensureData,readData,changeData,getSetting,putSetting,restoreData} from "./db.js";
import {newBackupKey,encryptSnapshot,decryptSnapshot} from "./crypto.js";
import {syncLedger} from "./sync.js";
const $=id=>document.getElementById(id);let data,editingOriginal=null,syncing=false,queuedSync=false;
const kindLabels={expense:"支出",income:"収入",refund:"返金",transfer:"振替",adjustment:"残高調整"};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const accountName=id=>data.accounts.find(a=>a.id===id)?.name??id;
function message(text,error=false){$("notice").hidden=false;$("notice").textContent=text;$("notice").className="notice"+(error?" error":"");}
async function action(fn){try{await fn();}catch(e){message(e.message,true);}}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));const a=el("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
async function save(fn,text="端末に保存しました"){const r=await changeData(fn);data=r.data;render();message(text);void runSync(true);}
function optionAccounts(select,selected){select.replaceChildren();for(const a of data.accounts){const o=el("option",a.name);o.value=a.id;select.append(o);}if(selected)select.value=selected;}
function button(text,fn,cls){const b=el("button",text,cls);b.type="button";b.addEventListener("click",()=>action(fn));return b;}
function render(){
  const month=$("month").value,summary=core.monthlySummary(data,month),estimated=core.monthlySummary(data,month,true);
  $("expense").textContent=core.yen(summary.netExpenseYen);$("income").textContent=core.yen(summary.incomeYen);$("estimated-expense").textContent=`確認待ちを含む見込み ${core.yen(estimated.netExpenseYen)}`;
  const pending=data.entries.filter(e=>e.pending).length+data.observations.filter(o=>o.status==="pending").length;
  $("pending-count").textContent=pending?String(pending):"";$("pending-total").textContent=`${pending}件`;
  const cards=$("account-cards");cards.replaceChildren();for(const a of data.accounts){const row=el("div",undefined,"account-row"),name=el("div",a.name);name.append(el("small",a.type==="credit"?`毎月${a.withdrawalDay??"—"}日引落`:a.type==="cash"?"手持ちの現金":"銀行口座"));row.append(name,el("strong",core.yen(core.balanceAt(data,a.id))));cards.append(row);}
  const cats=$("categories");cats.replaceChildren();if(!summary.categories.length)cats.append(el("p","承認した支出がここに表示されます","empty"));for(const c of summary.categories){const row=el("div",undefined,"category-row"),label=el("div",undefined,"category-label"),track=el("div",undefined,"bar-track"),bar=el("div",undefined,"bar");label.append(el("span",c.name),el("span",core.yen(c.amountYen)));bar.style.width=`${Math.max(0,Math.min(100,c.amountYen/Math.max(1,summary.netExpenseYen)*100))}%`;track.append(bar);row.append(label,track);cats.append(row);}
  const lastCash=data.observations.filter(o=>o.status==="approved"&&data.accounts.find(a=>a.id===o.accountId)?.type==="cash").sort((a,b)=>b.observedAt.localeCompare(a.observedAt))[0];
  $("cash-reminder").textContent=!lastCash||Date.now()-Date.parse(lastCash.observedAt)>14*86400000?"財布の実残高も、都合のよいときに確認してください。":"財布の残高は最近確認済みです。";
  renderEntries();renderObservations();renderAccounts();
  for(const id of ["observation-account","entry-account","entry-to-account"]){const s=$(id),prev=s.value;optionAccounts(s,prev);}
  $("connection").textContent=navigator.onLine?"端末に保存済み":"オフライン";
}
function renderEntries(){
  const list=$("entry-list");list.replaceChildren();const filter=$("entry-filter").value;
  const entries=[...data.entries].filter(e=>filter==="all"||core.entryState(e)===filter).sort((a,b)=>(b.pending?.data.date??b.settled?.data.date??"").localeCompare(a.pending?.data.date??a.settled?.data.date??""));
  if(!entries.length)list.append(el("p","表示する記録がありません","empty"));
  for(const e of entries){const t=e.pending?.data??e.settled?.data;if(!t){list.append(el("article","却下した入力候補。元メールの再取得による重複登録を防いでいます。","record"));continue;}
    const row=el("article",undefined,"record"),head=el("div",undefined,"record-head"),info=el("div"),state=core.entryState(e);
    info.append(el("span",state==="pending"?"確認待ち":state==="approved"?"承認済み":"却下済み",`badge ${state}`),el("span",t.merchant||kindLabels[t.kind],"record-title"));
    info.append(el("div",`${t.date} · ${kindLabels[t.kind]} · ${accountName(t.accountId)}${t.toAccountId?` → ${accountName(t.toAccountId)}`:""} · ${t.category||"費目なし"}`,"record-meta"));
    head.append(info,el("strong",core.yen(t.kind==="adjustment"?t.adjustmentYen:t.amountYen)));row.append(head);
    if(t.note)row.append(el("p",t.note,"record-note"));if(e.sourceKey)row.append(el("p",`元情報: ${e.sourceKey}`,"hint"));
    if(e.pending&&e.settled)row.append(el("p",`承認前の確定額: ${core.yen(e.settled.data.kind==="adjustment"?e.settled.data.adjustmentYen:e.settled.data.amountYen)}`,"hint"));
    const actions=el("div",undefined,"actions");actions.append(button(e.pending?"訂正する":"修正案を作る",()=>openEntry(e.id)));
    if(e.pending)actions.append(button("承認する",()=>save(d=>core.approveEntry(d,e.id),"取引を承認しました"),"primary"),button("却下する",()=>save(d=>core.rejectEntry(d,e.id),"入力候補を却下しました"),"danger"));row.append(actions);list.append(row);
  }
}
function renderObservations(){
  const list=$("observation-list");list.replaceChildren();if(!data.observations.length)list.append(el("p","スクショや申告の残高がここに表示されます","empty"));
  for(const o of [...data.observations].sort((a,b)=>b.observedAt.localeCompare(a.observedAt))){
    const row=el("article",undefined,"record"),head=el("div",undefined,"record-head"),info=el("div");info.append(el("span",o.status==="approved"?"確認済み":o.status==="rejected"?"却下済み":"確認待ち",`badge ${o.status}`),el("span",accountName(o.accountId),"record-title"),el("div",new Date(o.observedAt).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"}),"record-meta"));head.append(info,el("strong",core.yen(o.balanceYen)));row.append(head);
    const c=core.compareObservation(data,o),cols=el("div",undefined,"comparison");for(const[label,n]of [["計算上の残高",c.expectedYen],["スクショ・申告",o.balanceYen],["差額",c.differenceYen]]){const col=el("div");col.append(el("small",label),el("strong",core.yen(n)));cols.append(col);}row.append(cols);
    row.append(el("p",o.withdrawalConfirmed?"引落反映を確認済み":"引落反映は未確認。残高のみの画像では判定できません。","hint"));if(o.note)row.append(el("p",o.note,"record-note"));
    const actions=el("div",undefined,"actions");
    if(o.status==="pending")actions.append(button("この実残高を承認",()=>save(d=>core.approveObservation(d,o.id),"実残高を確認しました"),"primary"),button("却下",()=>save(d=>{const v=d.observations.find(v=>v.id===o.id);const before=core.clone(v);v.status="rejected";core.audit(d,"reject_observation",v.id,before,v);}),"danger"));
    if(o.status==="approved"&&c.differenceYen)actions.append(button("差額の修正案を作る",()=>{if(confirm("入出金明細と当日の取引を確認しましたか？ 原因が分からない差額は費目に割り当てず、残高調整の候補として保存します。"))return save(d=>core.adjustmentProposal(d,o.id),"残高調整の修正案を作りました。記録・承認で確認してください");}));row.append(actions);list.append(row);
  }
}
function renderAccounts(){const area=$("account-settings");area.replaceChildren();for(const a of data.accounts){const form=el("form",undefined,"account-form"),grid=el("div",undefined,"form-grid");const fields={};for(const[name,label,type,value]of [["name","呼び名","text",a.name],["openingBalanceYen","基準残高（円）","number",a.openingBalanceYen],["openingDate","基準日","date",a.openingDate]]){const l=el("label",label),input=el("input");input.type=type;input.value=value??"";if(type==="number")input.step="1";fields[name]=input;l.append(input);grid.append(l);}const select=el("select");for(const[value,label]of [["bank","銀行"],["cash","財布"],["credit","カード"]]){const o=el("option",label);o.value=value;select.append(o);}select.value=a.type;const label=el("label","種類");label.append(select);grid.append(label);const saveButton=el("button","保存");saveButton.type="submit";form.append(grid,saveButton);form.addEventListener("submit",event=>{event.preventDefault();void action(()=>save(d=>{const target=d.accounts.find(x=>x.id===a.id),before=core.clone(target);Object.assign(target,{name:fields.name.value.trim(),type:select.value,openingDate:fields.openingDate.value,openingBalanceYen:fields.openingBalanceYen.value===""?null:Number(fields.openingBalanceYen.value)});core.validateAccount(target);core.audit(d,"update_account",a.id,before,target);}));});area.append(form);}}
function openEntry(id=null){const e=id?data.entries.find(e=>e.id===id):null,t=e?.pending?.data??e?.settled?.data;editingOriginal=t?core.clone(t):null;$("entry-id").value=id??"";$("entry-title").textContent=id?"記録の訂正":"記録を追加";$("entry-date").value=t?.date??core.today();$("entry-kind").value=t?.kind??"expense";optionAccounts($("entry-account"),t?.accountId);optionAccounts($("entry-to-account"),t?.toAccountId??data.accounts.find(a=>a.type==="credit")?.id);$("entry-amount").value=t?(t.kind==="adjustment"?t.adjustmentYen:t.amountYen):"";$("entry-merchant").value=t?.merchant??"";$("entry-category").value=t?.category??"";$("entry-note").value=t?.note??"";$("entry-error").textContent="";updateKind();$("entry-dialog").showModal();}
function updateKind(){const kind=$("entry-kind").value;$("to-account-label").hidden=kind!=="transfer";$("entry-amount").min=kind==="adjustment"?"":"1";}
async function runSync(silent=false){if(!navigator.onLine)return;if(syncing){queuedSync=true;return;}syncing=true;queuedSync=false;$("sync-button").disabled=true;let failed=false;try{const result=await syncLedger();data=await readData();render();await renderSyncStatus();if(!silent){if(!result.configured)message("設定・バックアップで同期先を設定してください");else if(result.errors.length)message(`取得できなかった候補が${result.errors.length}件あります。${result.errors[0].message}`,true);else message(`${result.imported}件の候補を取得しました${result.backup?"。暗号化バックアップも送信しました":"。暗号化を設定するとバックアップを送れます"}`);}else if(result.errors?.length)message(result.errors[0].message,true);}catch(e){failed=true;message(`端末には保存済みです。${e.message}`,true);}finally{syncing=false;$("sync-button").disabled=false;if(queuedSync&&!failed)queueMicrotask(()=>void runSync(true));}}
async function renderSyncStatus(){const s=await getSetting("lastSync");$("sync-status").textContent=s?`最後の同期: ${new Date(s.at).toLocaleString("ja-JP")} · ${s.backup?"バックアップ同期済み":"暗号化バックアップ未設定"}`:"まだ同期していません";}
async function storageStatus(){const persistent=await navigator.storage?.persisted?.();$("storage-status").textContent=persistent?"端末への保存は保護されています。ブラウザーの設定で消したデータは、バックアップから復元してください。":"通常の保存領域を使用しています。バックアップも保存しておくと、端末の変更時に復元できます。";}
for(const b of document.querySelectorAll("nav button"))b.addEventListener("click",()=>{for(const v of document.querySelectorAll(".view"))v.hidden=v.id!==b.dataset.view;for(const n of document.querySelectorAll("nav button"))n.setAttribute("aria-selected",String(n===b));});
$("month").value=core.today().slice(0,7);$("month").addEventListener("change",render);$("entry-filter").addEventListener("change",renderEntries);$("new-entry").addEventListener("click",()=>openEntry());$("close-entry").addEventListener("click",()=>$("entry-dialog").close());$("entry-kind").addEventListener("change",updateKind);
$("entry-form").addEventListener("submit",async event=>{event.preventDefault();try{const kind=$("entry-kind").value;const t={kind,date:$("entry-date").value,accountId:$("entry-account").value,currency:"JPY",merchant:$("entry-merchant").value,category:$("entry-category").value,note:$("entry-note").value};if(kind==="adjustment"){t.adjustmentYen=Number($("entry-amount").value);if(editingOriginal?.observationId){t.observationId=editingOriginal.observationId;t.basisBalanceYen=editingOriginal.basisBalanceYen;}}else t.amountYen=Number($("entry-amount").value);if(kind==="transfer")t.toAccountId=$("entry-to-account").value;core.validateTransaction(t,data.accounts);await save(d=>core.proposeTransaction(d,t,{entryId:$("entry-id").value||undefined}),"確認待ちで保存しました");$("entry-dialog").close();}catch(e){$("entry-error").textContent=e.message;}});
$("observation-time").value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
$("observation-form").addEventListener("submit",event=>{event.preventDefault();void action(async()=>{const o={accountId:$("observation-account").value,observedAt:new Date($("observation-time").value).toISOString(),balanceYen:Number($("observation-amount").value),withdrawalConfirmed:$("withdrawal-confirmed").checked?true:null,note:$("observation-note").value};await save(d=>core.recordObservation(d,o),"実残高を確認待ちで保存しました");});});
$("sync-form").addEventListener("submit",event=>{event.preventDefault();void action(async()=>{const url=$("relay-url").value.trim();if(url){const u=new URL(url);if(u.pathname!=="/"||u.search||u.hash||u.username||u.password)throw new Error("同期先はドメインのみを指定してください");if(u.protocol!=="https:"&&!(u.protocol==="http:"&&["localhost","127.0.0.1"].includes(u.hostname)))throw new Error("同期先はHTTPSで指定してください");}await putSetting("relayUrl",url);await putSetting("viewerToken",$("viewer-token").value);message("接続設定を保存しました");await runSync();});});
$("key-form").addEventListener("submit",event=>{event.preventDefault();void action(async()=>{const keyInfo=await newBackupKey($("backup-password").value);await putSetting("backupKey",keyInfo);$("backup-password").value="";await save(d=>core.audit(d,"configure_backup_encryption",d.meta.ledgerId,null,{configured:true}),"暗号化を設定しました。復元用パスフレーズは別途保管してください");});});
$("backup-download").addEventListener("click",()=>action(async()=>{const key=await getSetting("backupKey");if(!key)throw new Error("先に暗号化を設定してください");download(await encryptSnapshot(await readData(),key),`ledger-backup-${core.today()}.json`);}));
$("plain-export").addEventListener("click",()=>action(async()=>download(await readData(),`ledger-${core.today()}.json`)));
$("analysis-export").addEventListener("click",()=>action(async()=>{const d=await readData();download({generatedAt:new Date().toISOString(),month:$("month").value,confirmed:core.monthlySummary(d,$("month").value),includingPending:core.monthlySummary(d,$("month").value,true),accounts:d.accounts.map(a=>({name:a.name,type:a.type,balanceYen:core.balanceAt(d,a.id)})),transactions:d.entries.filter(e=>e.settled?.data.date.startsWith($("month").value)).map(e=>({...e.settled.data,accountName:accountName(e.settled.data.accountId)}))},`ledger-analysis-${$("month").value}.json`);message("分析用データを保存しました。ChatGPTに添付すると内容を分析できます");}));
$("draft-import").addEventListener("change",event=>action(async()=>{const f=event.target.files[0];if(!f)return;if(f.size>2_000_000)throw new Error("入力ファイルが大きすぎます");const value=JSON.parse(await f.text());const drafts=Array.isArray(value)?value:value.drafts??[value];await save(d=>{for(const draft of drafts)core.importDraft(d,draft);},"入力候補を取り込みました");event.target.value="";}));
$("restore-button").addEventListener("click",()=>action(async()=>{const file=$("restore-file").files[0];if(!file)throw new Error("復元するファイルを選んでください");if(file.size>20_000_000)throw new Error("復元ファイルが大きすぎます");const value=JSON.parse(await file.text());let restored,keyInfo;if(value.format==="local-ledger-encrypted"){const v=await decryptSnapshot(value,$("restore-password").value);restored=v.data;keyInfo=v.keyInfo;}else restored=value;core.validateSnapshot(restored);if(!confirm(`口座${restored.accounts.length}件・取引${restored.entries.length}件の家計簿で現在の内容を置き換えます。復元しますか？`))return;data=(await restoreData(restored)).data;if(keyInfo)await putSetting("backupKey",keyInfo);$("restore-password").value="";render();message("家計簿を復元しました");void runSync(true);}));
$("add-account").addEventListener("click",()=>action(()=>save(d=>{d.accounts.push({id:crypto.randomUUID(),name:"新しい口座",type:"bank",openingDate:core.today(),openingBalanceYen:null,withdrawalDay:null});})));
$("persist-storage").addEventListener("click",()=>action(async()=>{await navigator.storage?.persist?.();await storageStatus();}));$("sync-button").addEventListener("click",()=>void runSync());window.addEventListener("online",()=>{render();void runSync(true);});window.addEventListener("offline",render);
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")void action(async()=>{data=await readData();render();void runSync(true);});});
await action(async()=>{data=await ensureData();render();$("relay-url").value=await getSetting("relayUrl")??"";$("viewer-token").value=await getSetting("viewerToken")??"";await renderSyncStatus();await storageStatus();if("serviceWorker"in navigator)await navigator.serviceWorker.register("./sw.js",{scope:"./"});void runSync(true);});
